name: 'Terraform test composite'

inputs:
  working_directory:
    required: true
    type: string
  tf_version:
    required: true
    type: string
  client_id:
    required: true
    type: string
  client_secret:
    required: true
    type: string
  subscription_id:
    required: true
    type: string
  tenant_id:
    required: true
    type: string
  backend_tf_rg:
    required: true
    type: string
  backend_tf_sa:
    required: true
    type: string
  backend_tfstate_name:
    required: true
    type: string
  tfstate_container:
    required: true
    type: string
  environment:
    required: true
    type: string
  github_token: 
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      id: init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        ARM_CLIENT_ID: ${{ inputs.client_id }}
        ARM_CLIENT_SECRET: ${{ inputs.client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.subscription_id }}
        ARM_TENANT_ID: ${{ inputs.tenant_id }}
      run: echo ${{ inputs.subscription_id }}