#cloud-config
package_upgrade: true
packages:
  - apache2
  - php
write_files:
  - owner: www-data:www-data
    path: /var/www/html/index.html
    permissions: '0644'
    content: |
      <!DOCTYPE html>
      <html>  
        <body>
          <p><?php echo "Hello Red Squad from host:".gethostname(); ?></p>
        </body>
      </html>
runcmd:
  - systemctl restart apache2