name: 'Terraform Deploy'
 
on:
  push:
    branches:
    - main
    paths:
      - 'terraform/**.tf'
      - 'environments/**.tfvars'
      - '.github/workflows/main.yaml'
  pull_request:

jobs:
  terraform:
    uses: ./.github/workflows/templates/terraform-terraform-deploy.yaml
    strategy:
      matrix:
        environment: 
          - 'dev'
          - 'prod'
      fail-fast: true
      max-parallel: 1
    with:
      environment: ${{ matrix.environment }}
      backend_tf_rg: ${{ secrets.BACKEND_RG }}
      backend_tf_sa: ${{ secrets.BACKEND_SA }}
      backend_tfstate_name: ${{ matrix.environment }}-tf-github
      tfstate_container: github-tf-state-${{ matrix.environment }}
      working_directory: terraform
    secrets:
      CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
