name: 'Terraform Deploy'
 
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**.tf'
      - 'environments/**.tfvars'
      - '.github/workflows/main.yaml'

env:
  TF_LOG: INFO

permissions:
  contents: read
  
jobs:
  terraform:
    name: 'Terraform'
    uses: ./.github/workflows/terraform-template.yaml
    strategy:
      fail-fast: true
      max-parallel: 1
    with:
      working_directory: terraform
    secrets:
      CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      BACKEND_TF_RG: ${{ secrets.BACKEND_RG }}
      BACKEND_TF_SA: ${{ secrets.BACKEND_SA }}
      TFVAR_ADMIN_PASSWORD: ${{ secrets.TF_VAR_admin_password }}