name: Terraform - template

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      tf_version:
        type: string
        default: 1.5.7
    secrets:
      CLIENT_ID:
        required: true
      CLIENT_SECRET:
        required: true
      SUBSCRIPTION_ID:
        required: true
      TENANT_ID:
        required: true
      BACKEND_TF_RG:
        required: true
      BACKEND_TF_SA:
        required: true
      TFVAR_ADMIN_PASSWORD:
        required: true
 
jobs:
  terraform-pr-plan:
    name: "Run Terraform PR Plan"
    environment: 'dev'
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      
      - name: Terraform PR
        id: terraform-pr
        uses: ./.github/actions/terraform-pr
        with:
            tf_version: ${{ inputs.tf_version }}
            client_id: ${{ secrets.CLIENT_ID }}
            client_secret: ${{ secrets.CLIENT_SECRET }}
            subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
            tenant_id: ${{ secrets.TENANT_ID }}
            backend_tf_rg: ${{ secrets.BACKEND_TF_RG }}
            backend_tf_sa: ${{ secrets.BACKEND_TF_SA }}
            environment: 'dev'
            github_token: ${{ secrets.GITHUB_TOKEN }}
            admin_pass: ${{ secrets.TFVAR_ADMIN_PASSWORD }}
            working_directory: ${{ inputs.working_directory }}

  terraform-deploy-dev:
    name: "Run Terraform - Dev"
    environment: 'dev'
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Terraform deploy
        id: terraform-deploy
        uses: ./.github/actions/terraform-deploy
        with:
            tf_version: ${{ inputs.tf_version }}
            client_id: ${{ secrets.CLIENT_ID }}
            client_secret: ${{ secrets.CLIENT_SECRET }}
            subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
            tenant_id: ${{ secrets.TENANT_ID }}
            backend_tf_rg: ${{ secrets.BACKEND_TF_RG }}
            backend_tf_sa: ${{ secrets.BACKEND_TF_SA }}
            environment: 'dev'
            admin_pass: ${{ secrets.TFVAR_ADMIN_PASSWORD }}
            working_directory: ${{ inputs.working_directory }}

  terraform-deploy-prod:
    name: "Run Terraform - Prod"
    environment: 'prod'
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Terraform deploy
        id: terraform-deploy
        uses: ./.github/actions/terraform-deploy
        with:
            tf_version: ${{ inputs.tf_version }}
            client_id: ${{ secrets.CLIENT_ID }}
            client_secret: ${{ secrets.CLIENT_SECRET }}
            subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
            tenant_id: ${{ secrets.TENANT_ID }}
            backend_tf_rg: ${{ secrets.BACKEND_TF_RG }}
            backend_tf_sa: ${{ secrets.BACKEND_TF_SA }}
            environment: 'prod'
            admin_pass: ${{ secrets.TFVAR_ADMIN_PASSWORD }}
            working_directory: ${{ inputs.working_directory }}
